version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST_CENTRO1=${DB_HOST_CENTRO1}
      - DB_HOST_CENTRO2=${DB_HOST_CENTRO2}
      - DB_NAME_CENTRO1=${DB_NAME_CENTRO1}
      - DB_NAME_CENTRO2=${DB_NAME_CENTRO2}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: 